@echo off
echo Renaming gitignore to .gitignore...
if exist gitignore (
    rename gitignore .gitignore
)
echo Staging all files...
git add .
echo Committing...
git commit -m "feat: World-class Super Admin Control Center + full project"
echo Setting branch to main...
git branch -M main
echo Pushing to GitHub...
git push -u origin main
echo Done!
